[workspace]
git_tag_enable = false
git_release_enable = false
changelog_update = false
semver_check = false
pr_labels = ["release"]

[[package]]
name = "ticit"
changelog_update = true
changelog_path = "CHANGELOG.md"
changelog_include = ["ticit_py"]
git_tag_enable = true
git_tag_name = "v{{ version }}"
git_release_enable = true
git_release_name = "v{{ version }}"

[[package]]
name = "ticit_py"
release = false
publish = false

[changelog]
protect_breaking_commits = true
