# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "Circuit",
    "MeasureResult",
    "ParseError",
    "PauliString",
    "Program",
    "SampleResult",
    "SimulatorError",
    "TableauSimulator",
    "compile",
    "neg",
    "parse",
    "parse_file",
    "pauli_identity",
    "pauli_string",
    "pauli_x",
    "pauli_y",
    "pauli_z",
    "sample",
    "sample_survivors",
]

__version__: builtins.str
@typing.final
class Circuit:
    r"""
    A parsed `.ticit`/Stim-style circuit.

    Call `circuit.compile(...)` when the circuit will be sampled.

    Examples:
        >>> import ticit
        >>> circuit = ticit.Circuit("H 0\nM 0\nDETECTOR rec[-1]")
        >>> (circuit.num_qubits, circuit.num_measurements, circuit.num_detectors)
        (1, 1, 1)
    """
    @property
    def num_qubits(self) -> builtins.int:
        r"""
        Number of qubits named by the circuit.
        """
    @property
    def num_measurements(self) -> builtins.int:
        r"""
        Number of measurement records produced by the circuit.
        """
    @property
    def num_detectors(self) -> builtins.int:
        r"""
        Number of detector declarations.
        """
    @property
    def num_observables(self) -> builtins.int:
        r"""
        Number of observable indices.
        """
    @property
    def num_exp_vals(self) -> builtins.int:
        r"""
        Number of expectation values produced by the circuit.
        """
    def __new__(cls, stim_text: builtins.str = '') -> Circuit:
        r"""
        Parses `stim_text` into a circuit. An empty string creates an empty circuit.
        """
    @staticmethod
    def from_text(stim_text: builtins.str) -> Circuit:
        r"""
        Parses a circuit from source text.
        """
    @staticmethod
    def from_file(path: builtins.str) -> Circuit:
        r"""
        Parses a circuit from a UTF-8 file.
        """
    def compile(self, postselection_mask: typing.Optional[typing.Sequence[builtins.int]] = None, *, backend: builtins.str = 'cpu', observable: builtins.int = 0, threads: builtins.int = 1, sample_chunk_shots: builtins.int = 0, batch_size: builtins.int = 0, gpu_chunk_shots: builtins.int = 1048576) -> Program:
        r"""
        Compiles this circuit into a reusable `Program`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class MeasureResult:
    r"""
    Result of a Pauli measurement.
    """
    @property
    def outcome(self) -> builtins.bool:
        r"""
        Observed eigenvalue bit: `False` is +1 and `True` is -1.
        """
    @property
    def probability(self) -> builtins.float:
        r"""
        Probability assigned to this outcome before projection.
        """
    @property
    def deterministic(self) -> builtins.bool:
        r"""
        Whether the state forced the outcome.
        """
    def __repr__(self) -> builtins.str: ...

class ParseError(builtins.ValueError):
    r"""
    A circuit failed to parse or lower.
    """
    ...

@typing.final
class PauliString:
    r"""
    A packed Pauli operator with a phase exponent of `i`.

    String position is the qubit index. Use `pauli_string("IXYZ")` to parse a
    dense literal, or construct identity storage with `PauliString(nqubits)` and
    set its bits explicitly.

    Examples:
        >>> import ticit
        >>> p = ticit.pauli_string("XYZ")
        >>> str(p)
        'XYZ'
        >>> str(-p)
        '-XYZ'
    """
    @property
    def nqubits(self) -> builtins.int:
        r"""
        Number of qubits represented by the operator.
        """
    @property
    def x(self) -> builtins.list[builtins.int]:
        r"""
        Copy of the packed LSB-first X words.
        """
    @property
    def z(self) -> builtins.list[builtins.int]:
        r"""
        Copy of the packed LSB-first Z words.
        """
    @property
    def phase_exponent(self) -> builtins.int:
        r"""
        Stored phase exponent of `i`, in `0..=3`.
        """
    def __new__(cls, nqubits: builtins.int = 0) -> PauliString:
        r"""
        Constructs identity on `nqubits` qubits.
        """
    @staticmethod
    def from_text(text: builtins.str) -> PauliString:
        r"""
        Parses a dense literal such as `"IXYZ"`; `_` is identity.
        """
    def xbit(self, q: builtins.int) -> builtins.bool:
        r"""
        Returns whether qubit `q` has an X component.
        """
    def zbit(self, q: builtins.int) -> builtins.bool:
        r"""
        Returns whether qubit `q` has a Z component.
        """
    def set_xbit(self, q: builtins.int, value: builtins.bool) -> None:
        r"""
        Sets or clears the X component on qubit `q`.
        """
    def set_zbit(self, q: builtins.int, value: builtins.bool) -> None:
        r"""
        Sets or clears the Z component on qubit `q`.
        """
    def set_phase(self, phase_exponent: builtins.int) -> None:
        r"""
        Sets the phase exponent modulo four.
        """
    def phase_shift(self, delta: builtins.int) -> None:
        r"""
        Adds `delta` to the phase exponent modulo four.
        """
    def has_nonidentity_body(self) -> builtins.bool:
        r"""
        Whether any qubit carries X, Y, or Z.
        """
    def same_body(self, other: PauliString) -> builtins.bool:
        r"""
        Structural body equality ignoring phase.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: PauliString) -> builtins.bool: ...
    def __mul__(self, other: PauliString) -> PauliString: ...
    def __neg__(self) -> PauliString: ...

@typing.final
class Program:
    r"""
    A compiled circuit that can be sampled repeatedly.

    Construct programs with `Circuit.compile`; this class has no public constructor.
    """
    @property
    def backend(self) -> builtins.str:
        r"""
        Selected execution backend: `"cpu"` or `"gpu"`.
        """
    @property
    def num_qubits(self) -> builtins.int:
        r"""
        Number of qubits in the circuit.
        """
    @property
    def num_measurements(self) -> builtins.int:
        r"""
        Number of measurement records in the circuit.
        """
    @property
    def num_detectors(self) -> builtins.int:
        r"""
        Number of detectors in the circuit.
        """
    @property
    def num_observables(self) -> builtins.int:
        r"""
        Number of observable indices in the circuit.
        """
    @property
    def num_exp_vals(self) -> builtins.int:
        r"""
        Number of expectation values in each result row.
        """
    @property
    def observable(self) -> builtins.int:
        r"""
        Observable index counted as a logical error.
        """
    @property
    def has_postselection(self) -> builtins.bool:
        r"""
        Whether detector postselection is active.
        """
    def sample(self, shots: builtins.int, seed: typing.Optional[builtins.int] = None, *, bit_packed: builtins.bool = False) -> SampleResult:
        r"""
        Samples this compiled circuit and returns per-shot records and counters.

        With `bit_packed=True`, each record array has `ceil(num_bits / 8)`
        columns and uses NumPy's little bit order.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SampleResult:
    r"""
    Per-shot records, aggregate counters, and timing from one sampling call.
    """
    @property
    def measurements(self) -> numpy.typing.NDArray[numpy.uint8]:
        r"""
        Row-major `uint8` measurement array.
        """
    @property
    def detectors(self) -> numpy.typing.NDArray[numpy.uint8]:
        r"""
        Row-major `uint8` detector array.
        """
    @property
    def observables(self) -> numpy.typing.NDArray[numpy.uint8]:
        r"""
        Row-major `uint8` observable array.
        """
    @property
    def exp_vals(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        `float64` array shaped `(passed_shots, num_exp_vals)`.
        """
    @property
    def total_shots(self) -> builtins.int:
        r"""
        Attempted shots. Alias of `shots`.
        """
    @property
    def shots(self) -> builtins.int:
        r"""
        Attempted shots.
        """
    @property
    def discards(self) -> builtins.int:
        r"""
        Shots rejected by detector postselection. Alias of `discarded`.
        """
    @property
    def discarded(self) -> builtins.int:
        r"""
        Shots rejected by detector postselection.
        """
    @property
    def passed_shots(self) -> builtins.int:
        r"""
        Shots retained after postselection. Alias of `accepted`.
        """
    @property
    def accepted(self) -> builtins.int:
        r"""
        Shots retained after postselection.
        """
    @property
    def logical_errors(self) -> builtins.int:
        r"""
        Accepted shots where the selected observable was one.
        """
    @property
    def observable_ones(self) -> numpy.typing.NDArray[numpy.uint64]:
        r"""
        `uint64` count for every observable column.
        """
    @property
    def observable(self) -> builtins.int:
        r"""
        Observable index represented by `logical_errors`.
        """
    @property
    def compile_s(self) -> builtins.float:
        r"""
        Circuit parsing/planning time in seconds.
        """
    @property
    def presample_s(self) -> builtins.float:
        r"""
        Exogenous-noise generation time in seconds.
        """
    @property
    def execute_s(self) -> builtins.float:
        r"""
        Circuit execution time in seconds.
        """
    @property
    def sample_s(self) -> builtins.float:
        r"""
        Total steady-state sampling time in seconds.
        """
    @property
    def active_threads(self) -> builtins.int:
        r"""
        CPU worker count used by the call; one for GPU sampling.
        """
    @property
    def bit_packed(self) -> builtins.bool:
        r"""
        Whether the three bit arrays pack eight bits into each byte.
        """
    @property
    def discard_rate(self) -> builtins.float:
        r"""
        Fraction of attempted shots rejected by postselection, or NaN for zero shots.
        """
    @property
    def logical_error_rate(self) -> builtins.float:
        r"""
        Fraction of accepted shots with a logical error, or NaN if none passed.
        """
    def __iter__(self) -> typing.Any: ...
    def __repr__(self) -> builtins.str: ...

class SimulatorError(builtins.RuntimeError):
    r"""
    A simulator operation failed on the live quantum state.
    """
    ...

@typing.final
class TableauSimulator:
    r"""
    A procedural Clifford+T state simulator shaped like Stim's TableauSimulator.

    Operations apply immediately. Qubit-writing operations grow the register;
    measurements return `MeasureResult`; non-collapsing `peek_*` calls reject
    qubits outside the current register.

    Examples:
        >>> import ticit
        >>> sim = ticit.TableauSimulator(2, seed=7)
        >>> sim.h(0)
        >>> sim.cx(0, 1)
        >>> sim.peek_observable_expectation(ticit.pauli_string("XX"))
        1.0
    """
    @property
    def num_qubits(self) -> builtins.int:
        r"""
        Current register size.
        """
    @property
    def rank(self) -> builtins.int:
        r"""
        Number of live amplitude terms.
        """
    def __new__(cls, num_qubits: builtins.int, seed: typing.Optional[builtins.int] = None) -> TableauSimulator:
        r"""
        Starts in `|0...0>`; `seed=None` uses OS entropy.
        """
    def reseed_rng(self, seed: builtins.int) -> None:
        r"""
        Reseeds outcome sampling without changing the state.
        """
    def restore_rng_from(self, snapshot: TableauSimulator) -> None:
        r"""
        Copies the RNG position from `snapshot` without changing the state.
        """
    def h(self, q: builtins.int) -> None:
        r"""
        Hadamard on `q`.
        """
    def s(self, q: builtins.int) -> None:
        r"""
        Phase gate S on `q`.
        """
    def s_dag(self, q: builtins.int) -> None:
        r"""
        S dagger on `q`.
        """
    def x(self, q: builtins.int) -> None:
        r"""
        Pauli X on `q`.
        """
    def y(self, q: builtins.int) -> None:
        r"""
        Pauli Y on `q`.
        """
    def z(self, q: builtins.int) -> None:
        r"""
        Pauli Z on `q`.
        """
    def sqrt_x(self, q: builtins.int) -> None:
        r"""
        Square-root X on `q`.
        """
    def sqrt_x_dag(self, q: builtins.int) -> None:
        r"""
        Square-root X dagger on `q`.
        """
    def sqrt_y(self, q: builtins.int) -> None:
        r"""
        Square-root Y on `q`.
        """
    def sqrt_y_dag(self, q: builtins.int) -> None:
        r"""
        Square-root Y dagger on `q`.
        """
    def c_xyz(self, q: builtins.int) -> None:
        r"""
        Order-three Pauli cycle X -> Y -> Z -> X.
        """
    def c_zyx(self, q: builtins.int) -> None:
        r"""
        Inverse Pauli cycle X -> Z -> Y -> X.
        """
    def h_xy(self, q: builtins.int) -> None:
        r"""
        Hadamard-like exchange of X and Y.
        """
    def h_yz(self, q: builtins.int) -> None:
        r"""
        Hadamard-like exchange of Y and Z.
        """
    def cx(self, control: builtins.int, target: builtins.int) -> None:
        r"""
        CNOT from `control` onto `target`.
        """
    def cnot(self, control: builtins.int, target: builtins.int) -> None:
        r"""
        CNOT alias matching Stim's spelling.
        """
    def cy(self, control: builtins.int, target: builtins.int) -> None:
        r"""
        Controlled Y from `control` onto `target`.
        """
    def cz(self, a: builtins.int, b: builtins.int) -> None:
        r"""
        Controlled Z on `a` and `b`.
        """
    def swap(self, a: builtins.int, b: builtins.int) -> None:
        r"""
        Swaps `a` and `b`.
        """
    def iswap(self, a: builtins.int, b: builtins.int) -> None:
        r"""
        ISWAP on `a` and `b`.
        """
    def iswap_dag(self, a: builtins.int, b: builtins.int) -> None:
        r"""
        ISWAP dagger on `a` and `b`.
        """
    def xcx(self, control: builtins.int, target: builtins.int) -> None:
        r"""
        X-controlled X.
        """
    def xcy(self, control: builtins.int, target: builtins.int) -> None:
        r"""
        X-controlled Y.
        """
    def xcz(self, control: builtins.int, target: builtins.int) -> None:
        r"""
        X-controlled Z.
        """
    def ycx(self, control: builtins.int, target: builtins.int) -> None:
        r"""
        Y-controlled X.
        """
    def ycy(self, control: builtins.int, target: builtins.int) -> None:
        r"""
        Y-controlled Y.
        """
    def ycz(self, control: builtins.int, target: builtins.int) -> None:
        r"""
        Y-controlled Z.
        """
    def zcx(self, control: builtins.int, target: builtins.int) -> None:
        r"""
        Z-controlled X, equivalent to CNOT.
        """
    def zcy(self, control: builtins.int, target: builtins.int) -> None:
        r"""
        Z-controlled Y.
        """
    def zcz(self, a: builtins.int, b: builtins.int) -> None:
        r"""
        Z-controlled Z, equivalent to CZ.
        """
    def pauli(self, pauli: PauliString) -> None:
        r"""
        Applies a Pauli operator to the state.
        """
    def controlled_pauli(self, control: PauliString, target: PauliString) -> None:
        r"""
        Applies commuting control and target Pauli axes.
        """
    def t(self, q: builtins.int) -> None:
        r"""
        Applies T on `q`.
        """
    def t_dag(self, q: builtins.int) -> None:
        r"""
        Applies T dagger on `q`.
        """
    def t_pauli(self, axis: PauliString, adjoint: builtins.bool) -> None:
        r"""
        Applies a T rotation about `axis`; `adjoint=True` selects T dagger.
        """
    def ccz(self, a: builtins.int, b: builtins.int, c: builtins.int) -> None:
        r"""
        Applies CCZ to three distinct qubits.
        """
    def measure(self, q: builtins.int) -> MeasureResult:
        r"""
        Measures Z on `q` and collapses the state.
        """
    def measure_observable(self, observable: PauliString) -> MeasureResult:
        r"""
        Measures a Hermitian Pauli observable and collapses the state.
        """
    def postselect_observable(self, observable: PauliString, desired_value: builtins.bool) -> MeasureResult:
        r"""
        Forces a Pauli measurement to `desired_value`.
        """
    def postselect_z(self, q: builtins.int, desired_value: builtins.bool) -> MeasureResult:
        r"""
        Forces a Z measurement on `q`.
        """
    def postselect_x(self, q: builtins.int, desired_value: builtins.bool) -> MeasureResult:
        r"""
        Forces an X measurement on `q`.
        """
    def postselect_y(self, q: builtins.int, desired_value: builtins.bool) -> MeasureResult:
        r"""
        Forces a Y measurement on `q`.
        """
    def peek_observable_expectation(self, observable: PauliString) -> builtins.float:
        r"""
        Returns a Pauli expectation without collapsing the state.
        """
    def peek_x(self, q: builtins.int) -> builtins.float:
        r"""
        Returns the X expectation on `q` without measuring.
        """
    def peek_y(self, q: builtins.int) -> builtins.float:
        r"""
        Returns the Y expectation on `q` without measuring.
        """
    def peek_z(self, q: builtins.int) -> builtins.float:
        r"""
        Returns the Z expectation on `q` without measuring.
        """
    def reset(self, q: builtins.int) -> None:
        r"""
        Resets `q` to |0>.
        """
    def reset_z(self, q: builtins.int) -> None:
        r"""
        Resets `q` to |0>.
        """
    def reset_x(self, q: builtins.int) -> None:
        r"""
        Resets `q` to |+>.
        """
    def reset_y(self, q: builtins.int) -> None:
        r"""
        Resets `q` to |+i>.
        """
    def state_vector(self) -> builtins.list[builtins.complex]:
        r"""
        Reconstructs the dense state vector; intended for small registers.
        """
    def __repr__(self) -> builtins.str: ...

def compile(stim_text: builtins.str, postselection_mask: typing.Optional[typing.Sequence[builtins.int]] = None, expected_detectors: typing.Optional[typing.Sequence[builtins.int]] = None, expected_observables: typing.Optional[typing.Sequence[builtins.int]] = None, normalize_syndromes: builtins.bool = False, *, backend: builtins.str = 'cpu', observable: builtins.int = 0, threads: builtins.int = 1, sample_chunk_shots: builtins.int = 0, batch_size: builtins.int = 0, gpu_chunk_shots: builtins.int = 1048576) -> Program:
    r"""
    Compiles circuit text into a reusable `Program`.

    The first five parameters mirror Clifft's `compile` call. ticit uses raw
    detector and observable parity, so reference normalization parameters must
    remain unset. `backend="gpu"` requires a package built with Cargo feature
    `gpu`; the GPU currently supports either no detector postselection or all
    detectors postselected.

    Args:
        stim_text: Circuit in ticit's Stim-style text format.
        postselection_mask: Zero/nonzero flag for each detector.
        expected_detectors: Reserved for Clifft call compatibility; unsupported.
        expected_observables: Reserved for Clifft call compatibility; unsupported.
        normalize_syndromes: Reserved for Clifft call compatibility; unsupported.
        backend: `"cpu"` or `"gpu"`.
        observable: Observable index counted as a logical error.
        threads: CPU worker count.
        sample_chunk_shots: CPU shots per scheduling chunk; zero selects ticit's default.
        batch_size: CPU execution batch size; zero selects ticit's default.
        gpu_chunk_shots: Maximum shots in one GPU launch group.

    Examples:
        >>> import ticit
        >>> program = ticit.compile("H 0\nM 0\nOBSERVABLE_INCLUDE(0) rec[-1]", threads=1)
        >>> program.backend
        'cpu'
    """

def neg(pauli: PauliString) -> PauliString:
    r"""
    Returns a copy of `pauli` multiplied by -1.
    """

def parse(text: builtins.str) -> Circuit:
    r"""
    Parses a quantum circuit from source text.

    Examples:
        >>> import ticit
        >>> ticit.parse("M 0").num_measurements
        1
    """

def parse_file(path: builtins.str) -> Circuit:
    r"""
    Parses a quantum circuit from a UTF-8 file.
    """

def pauli_identity(nqubits: builtins.int) -> PauliString:
    r"""
    Constructs identity on `nqubits` qubits.
    """

def pauli_string(text: builtins.str) -> PauliString:
    r"""
    Parses a dense Pauli literal such as `"IXYZ"`.
    """

def pauli_x(nqubits: builtins.int, q: builtins.int) -> PauliString:
    r"""
    Constructs X on qubit `q` and identity elsewhere.
    """

def pauli_y(nqubits: builtins.int, q: builtins.int) -> PauliString:
    r"""
    Constructs Y on qubit `q` and identity elsewhere.
    """

def pauli_z(nqubits: builtins.int, q: builtins.int) -> PauliString:
    r"""
    Constructs Z on qubit `q` and identity elsewhere.
    """

def sample(program: Program, shots: builtins.int, seed: typing.Optional[builtins.int] = None, *, bit_packed: builtins.bool = False) -> SampleResult:
    r"""
    Samples a compiled program and returns per-shot records and counters.

    `seed=None` uses OS-provided entropy. A fixed seed makes a call
    reproducible. Postselected programs return one row per surviving shot.

    Examples:
        >>> import ticit
        >>> result = ticit.sample(ticit.compile("M 0"), shots=20, seed=5)
        >>> (result.total_shots, result.passed_shots, result.discards)
        (20, 20, 0)
    """

def sample_survivors(program: Program, shots: builtins.int, seed: typing.Optional[builtins.int] = None, keep_records: builtins.bool = False, *, bit_packed: builtins.bool = False) -> SampleResult:
    r"""
    Clifft-compatible postselected sampling with optional survivor records.
    """
